name: Run Stream Extractor (v3)
on:
  schedule:
    - cron: '0 */2 * * *'
  pull_request:
      branches:
        - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps: 
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
            python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # YENİ: YouTube uyumluluğu için 'yt-dlp' eklendi
          pip install streamlink yt-dlp
      
      - name: Debug - Check config file
        run: |
          echo "=== Config file content (config.json) ==="
          cat config.json
          echo ""
          echo "=== Current directory ==="
          pwd
          ls -la
      
      - name: Execute py script (using v3)
        run: |
          # YENİ: main_v2.py script'ini çalıştır
          python main_v2.py config.json
          echo ""
          echo "=== Script completed, checking output ==="
          ls -la
          # config.json'daki 'folder' ayarını kontrol et (örn: 'streams')
          if [ -d "streams" ]; then
            echo "Streams folder exists:"
            ls -la streams/
          else
            echo "ERROR: 'streams' folder not created!"
          fi
      
      - name: Commit and push files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git status
          git diff --quiet && git diff --staged --quiet || git commit -m "updated streams $(date +'%Y-%m-%d %H:%M:%S')"
          git push