name: PPV Stream Fetcher

on:
  schedule:
    # Run every hour on the hour
    - cron: '0 * * * *'
  workflow_dispatch:
    # Allow manual trigger

jobs:
  fetch-streams:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install aiohttp playwright
        playwright install
        playwright install-deps
        
    - name: Run PPV script
      run: |
        python ppv.py
        
    - name: Commit changes
      if: success()
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add PPVLand.m3u8
        git diff --quiet && git diff --staged --quiet || 
          (git commit -m "Update PPV streams [skip ci]" && 
           git push) || echo "No changes to commit"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}