# Workflow'un adı
name: M3U Playlist Güncelleyici

on:
  # 1. Workflow'u manuel olarak çalıştırmak için (GitHub arayüzünden)
  workflow_dispatch:

  # 2. Her gün 03:00 UTC'de (Türkiye saati ile sabah 6) otomatik çalıştır
  schedule:
    - cron: '0 3 * * *'

jobs:
  update-playlist:
    # Job'un adı
    name: Playlist'i İndir ve Güncelle
    # Çalışacağı işletim sistemi
    runs-on: ubuntu-latest

    # GEREKLİ: Bu job'a depoya yazma (commit/push) izni ver
    permissions:
      contents: write

    steps:
      # Adım 1: Depodaki kodları (Python script'i dahil) indir
      - name: Depoyu Klonla (Checkout)
        uses: actions/checkout@v4

      # Adım 2: Python 3.x ortamını kur
      - name: Python 3.x Kur
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # Python versiyonunu belirleyebilirsiniz

      # Adım 3: Gerekli Python kütüphanelerini (requests) yükle
      - name: Bağımlılıkları Yükle
        run: |
          python -m pip install --upgrade pip
          pip install requests

      # Adım 4: Python script'ini çalıştır (Bu, turkey_first_playlist.m3u dosyasını oluşturmalı)
      - name: Playlist İşleyici Script'ini Çalıştır
        run: python translate_playlist.py

      # YENİ HATA AYIKLAMA ADIMI:
      # Python script'i çalıştıktan sonra dosyanın gerçekten oluşturulup oluşturulmadığını kontrol et
      - name: Dosyaları Listele (Hata Ayıklama)
        run: |
          echo "Script çalıştıktan sonraki dosya listesi:"
          ls -l

      # Adım 5: Oluşturulan dosyayı depoya commit'le ve push'la
      - name: Değişiklikleri Kaydet (Commit & Push)
        run: |
          # Git için bot kimliğini ayarla
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

          # Sadece 'turkey_first_playlist.m3u' dosyasını ekle
          git add turkey_first_playlist.m3u

          # Değişiklik olup olmadığını kontrol et.
          if ! git diff --staged --quiet; then
            echo "Değişiklikler algılandı, commit atılıyor..."
            git commit -m "Otomatik M3U playlist güncellemesi"
            git push
          else
            echo "Playlist'te değişiklik yok. Commit atılmadı."
          fi