Name: taraftarium24 fayli Links

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  extract:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          pip install playwright

      - name: Install Playwright browsers
        run: |
          playwright install chromium

      - name: Run taraftarium24.py
        run: python taraftarium24.py

      - name: Commit and Push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Auto-update m3u8 files"
            
            # --- HATA ÇÖZÜMÜ ---
            # 'git push' yapmadan önce sunucudaki olası yeni değişiklikleri
            # 'rebase' moduyla al. Bu, "fetch first" hatasını çözer.
            git pull --rebase
            # --- ÇÖZÜM SONU ---
            
            git push
          fi