name: M3U Oluşturucu (YouTube Destekli)

on:
  # 1. "main" branch'ine bir "push" (kayıt) yapıldığında (dosyalar değişince)
  push:
    branches: [ "main", "master" ]
    paths:
      - 'channels.json'
      - 'build_m3u.py'
      - '.github/workflows/main.yml' # İş akışının kendisi değişirse
      
  # 2. Manuel olarak çalıştırma (Actions sekmesindeki "Run workflow" butonu)
  workflow_dispatch:

  # 3. Zamanlanmış Görev (SCHEDULE)
  # Her 6 saatte bir çalışarak YouTube linklerini taze tutar
  schedule:
    - cron: '0 */6 * * *'

jobs:
  build-m3u-playlist:
    runs-on: ubuntu-latest

    steps:
      # Adım 1: Depodaki kodları (dosyaları) sanal makineye indir
      - name: Depoyu Kopyala
        uses: actions/checkout@v4

      # Adım 2: Python 3.10 ortamını kur
      - name: Python 3.10 Kur
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Adım 3: yt-dlp aracını kur
      - name: yt-dlp Kurulumu
        run: |
          pip install yt-dlp
          
      # Adım 4: M3U oluşturucu Python script'ini çalıştır
      - name: M3U Listesini Oluştur
        run: |
          python build_m3u.py
          
      # Adım 5: YENİ DÜZELTİLMİŞ COMMIT ADIMI
      # Oluşan playlist.m3u dosyasını depoya geri kaydet (Commit)
      - name: Değişiklikleri Depoya Kaydet (Add & Commit)
        uses: EndBug/add-and-commit@v9 # Hata veren eylem yerine bunu kullanıyoruz
        with:
          # Eklenecek dosya(lar). Sadece 'playlist.m3u'yu izle.
          add: 'playlist.m3u'
          
          # Commit atacak bot'un adı ve e-postası
          author_name: GitHub Actions Bot
          author_email: actions@github.com
          
          # Commit mesajı
          message: 'Otomatik: playlist.m3u (YT linkleri) güncellendi'
          
          # 'add' ile bulunan bir değişiklik yoksa boş commit atma
          default_author: github_actions